const MessageConstants = {
  ALLMESSAGES_RECEIVED: "ALLMESSAGES_RECEIVED",
  MESSAGES_RECEIVED: "MESSAGES_RECEIVED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_REMOVED: "MESSAGE_REMOVED"
};

module.exports = MessageConstants;
