# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(guest: false, username: "knope", password: "123456", fname: "Leslie", lname: "Knope", email: "what_would_leslie_do@parks&app.com")
User.create(guest: false, username: "ann", password: "123456", fname: "Ann", lname: "Perkins", email: "beautiful_tropical_fish@parks&app.com")
User.create(guest: false, username: "ben", password: "123456", fname: "Ben", lname: "Wyatt", email: "cones_of_dunshire@parks&app.com")
User.create(guest: false, username: "swanson", password: "123456", fname: "Ron", lname: "Swanson", email: "capitalism@parks&app.com")
User.create(guest: false, username: "april", password: "123456", fname: "April", lname: "Ludgate", email: "I_am_half_wolf@parks&app.com")
User.create(guest: false, username: "andy", password: "123456", fname: "Andy", lname: "Dwyer", email: "eagle_one@parks&app.com")
User.create(guest: false, username: "tom", password: "123456", fname: "Tom", lname: "Haverford", email: "treat_yo_self@parks&app.com")
User.create(guest: false, username: "jerry", password: "123456", fname: "Garry", lname: "Gergich", email: "gayle_and_i@parks&app.com")

Room.create(title: 'general', channel: true)
RoomUser.create(room_id: 1, user_id: 1)
RoomUser.create(room_id: 1, user_id: 2)
RoomUser.create(room_id: 1, user_id: 3)
RoomUser.create(room_id: 1, user_id: 4)
RoomUser.create(room_id: 1, user_id: 5)
RoomUser.create(room_id: 1, user_id: 6)
RoomUser.create(room_id: 1, user_id: 7)
RoomUser.create(room_id: 1, user_id: 8)
Message.create(user_id: 1, body: "I would like to be president someday, so no, I've not smoked marijuana. I ate a brownie once at a party in college. It was intense. It was kind of indescribable, actually. I felt like I was floating. Turns out there wasn't any pot in the brownie. It was just an insanely good brownie.", room_id: 1)
Message.create(user_id: 4, body: "Anne was getting a little chummy. When people get a little too chummy with me I like to call them by the wrong name to let them know I don't really care about them.", room_id: 1)
Message.create(user_id: 5, body: "That's a really nice move.", room_id: 1)
Message.create(user_id: 4, body: "Thank you.", room_id: 1)
Message.create(user_id: 5, body: "You're welcome, Lester.", room_id: 1)
Message.create(user_id: 3, body: "Hey, guys. In case you didn't notice, we can send snippets of source code to each other here like the one below.", room_id: 1)
Message.create(user_id: 3, body: "https://gist.github.com/bb6defd7866f7392ecacac78891c71e6", room_id: 1)
Message.create(user_id: 3, body: "Cool, huh?", room_id: 1)
Message.create(user_id: 5, body: "Nerd.", room_id: 1)

Room.create(title: 'leslie_quotes', channel: true)
RoomUser.create(room_id: 2, user_id: 1)
RoomUser.create(room_id: 2, user_id: 2)
RoomUser.create(room_id: 2, user_id: 3)
Message.create(user_id: 1, body: "We need to remember what's important in life: friends, waffles, work. Or waffles, friends, work. But work has to come third.", room_id: 2)
Message.create(user_id: 1, body: "These people are members of the community that care about where they live. So what I hear when I’m being yelled at is people caring loudly at me.", room_id: 2)
Message.create(user_id: 1, body: "I’m a feminist, OK? I would never ever go to a strip club. I’ve gone on record that if I had to have a stripper’s name, it would be Equality.", room_id: 2)
Message.create(user_id: 1, body: "I am big enough to admit that I am often inspired by myself.", room_id: 2)
Message.create(user_id: 1, body: "The bankrupt government of Pawnee has been shut down all summer so it’s been three months of no work, no meetings, no memos, no late nights, nothing. I wouldn’t wish it on my worst enemy.", room_id: 2)
Message.create(user_id: 1, body: "Guys love it when you can show them you’re better than they are at something they love.", room_id: 2)
Message.create(user_id: 1, body: "Sometimes when you make an omelet you’ve gotta break a few eggs. What’s the alternative? No omelets at all? Who wants to live in that kind of world? Maybe birds. Then all their babies would live.", room_id: 2)
Message.create(user_id: 1, body: "I would like to be president someday, so no, I've not smoked marijuana. I ate a brownie once at a party in college. It was intense. It was kind of indescribable, actually. I felt like I was floating. Turns out there wasn't any pot in the brownie. It was just an insanely good brownie.", room_id: 2)
Message.create(user_id: 3, body: "https://gist.github.com/9f28c901016b336121da8bad14ac9ab9", room_id: 2)



Room.create(title: 'medical_history', channel: true)
RoomUser.create(room_id: 3, user_id: 2)
RoomUser.create(room_id: 3, user_id: 3)
RoomUser.create(room_id: 3, user_id: 4)
Message.create(user_id: 3, body: "https://gist.github.com/e954017c46acd9cea036a41157aecbd9", room_id: 3)
Message.create(user_id: 2, body: "Ron, you redacted all the information.", room_id: 3)
Message.create(user_id: 4, body: "I answered some of them.", room_id: 3)
Message.create(user_id: 2, body: "For date of birth, you wrote spring time.", room_id: 3)
Message.create(user_id: 4, body: "Which is true.", room_id: 3)
Message.create(user_id: 2, body: "Everything you write down is confidential. We need you to give real answers.", room_id: 3)
Message.create(user_id: 4, body: "Fine.", room_id: 3)
Message.create(user_id: 2, body: "How many drinks of alcohol do you consume a week?", room_id: 3)
Message.create(user_id: 4, body: "One.", room_id: 3)
Message.create(user_id: 2, body: "That’s it? One drink?", room_id: 3)
Message.create(user_id: 4, body: "One shelf.", room_id: 3)
Message.create(user_id: 2, body: "Do you exercise?", room_id: 3)
Message.create(user_id: 4, body: "Yes. Lovemaking and woodworking.", room_id: 3)
Message.create(user_id: 2, body: "Do you have any history of mental illness in your family?", room_id: 3)
Message.create(user_id: 4, body: "I have an uncle who does yoga.", room_id: 3)

Room.create(title: 'marchtember_oneteenth', channel: true)
RoomUser.create(room_id: 4, user_id: 4)
RoomUser.create(room_id: 4, user_id: 5)
Message.create(user_id: 5, body: "So you know how you love me because you haven’t had a single meeting with anybody since I became your assistant? That’s because every time someone calls and requests a meeting with you, I schedule it for March 31st.", room_id: 4)
Message.create(user_id: 4, body: "Why?", room_id: 4)
Message.create(user_id: 5, body: "Because I didn’t think March 31 existed.", room_id: 4)
Message.create(user_id: 4, body: "So then how many meetings do I have today?", room_id: 4)
Message.create(user_id: 5, body: "93", room_id: 4)
Message.create(user_id: 5, body: "Do you want me to postpone the rest or I can set myself on fire and create a diversion?", room_id: 4)
Message.create(user_id: 5, body: "@dan: How about June 50th? Do you think you could come back today at 2:65? He’s available then.", room_id: 4)
Message.create(user_id: 5, body: "@dan: It looks like the only other day he has open is Marchtember oneteenth. Does that work, sir?", room_id: 4)

Room.create(title: 'janet_snakehole', channel: true)
RoomUser.create(room_id: 5, user_id: 5)
RoomUser.create(room_id: 5, user_id: 6)
Message.create(user_id: 5, body: "Ring a ding, ding who's calling? Oh is it Janet Snakehole? Why yes it is and who is she calling for? Mr. Bert Macklin and I'll tell you another thing boss, villain there ya go your goin real fast and now who's this Sorry Charlie? This sad sack of potatoes.", room_id: 5)
Message.create(user_id: 6, body: "Oh honey, please. I love you. No offense, but Bert Macklin died last night after the tenth shot of Snake Juice.", room_id: 5)
Message.create(user_id: 5, body: ":sad_face: Okay, sorry. :turn_around_and_leave:", room_id: 5)
Message.create(user_id: 6, body: "...", room_id: 5)
Message.create(user_id: 6, body: "Miss Snakehole.", room_id: 5)
Message.create(user_id: 6, body: "You think I'd let you get away that easily?", room_id: 5)
Message.create(user_id: 5, body: ":smile:", room_id: 5)
Message.create(user_id: 6, body: "Bert Macklin may be dead, but I'm his brother Kip Hackman.", room_id: 5)
Message.create(user_id: 6, body: "I know you boosted those paintings.", room_id: 5)
Message.create(user_id: 5, body: "Maybe it was me, but I'll never tell you where they are and you'll never have my body either. :run:", room_id: 5)

Room.create(title: 'beauty_pageant', channel: true)
RoomUser.create(room_id: 6, user_id: 1)
RoomUser.create(room_id: 6, user_id: 5)
Message.create(user_id: 5, body: "So, I was just at the grind and I thought you might want an iced mocha with extra, extra whipped cream.", room_id: 6)
Message.create(user_id: 1, body: "Oh, my. Thank you so much, April. Wow.", room_id: 6)
Message.create(user_id: 5, body: "You're welcome. Oh, by the way, completely unrelated, I just signed up for the Miss Pawnee Beauty Pageant.", room_id: 6)
Message.create(user_id: 1, body: "That's wonderful. You know, that is why I decided to become a judge. So that awesome girls like you who are not, you know, classically hot, can be rewarded for their intelligence and savvy.", room_id: 6)
Message.create(user_id: 5, body: ":to_camera: Beauty pageants are idiotic, but I found out that the winner of the Miss Pawnee pageant gets 600 dollars. I can be idiotic for 600 dollars.", room_id: 6)
Message.create(user_id: 5, body: "So are you gonna vote for me, sister?", room_id: 6)
Message.create(user_id: 1, body: "April, it's unethical for me to show you favoritism. You and I are like family.", room_id: 6)
Message.create(user_id: 5, body: "The coffee's seven dollars.", room_id: 6)
Message.create(user_id: 1, body: "Yes, right. Of course.", room_id: 6)

Room.create(title: 'swanson_quotes', channel: true)
RoomUser.create(room_id: 7, user_id: 1)
RoomUser.create(room_id: 7, user_id: 3)
RoomUser.create(room_id: 7, user_id: 4)
Message.create(user_id: 4, body: "History began on July 4, 1776. Everything that happened before that was a mistake.", room_id: 7)
Message.create(user_id: 4, body: "@waiter: Just give me all the bacon and eggs you have. Wait…wait. I worry what you just heard was: Give me a lot of bacon and eggs. What I said was: Give me all the bacon and eggs you have. Do you understand?", room_id: 7)
Message.create(user_id: 4, body: "Strippers do nothing for me. I like a strong salt-of-the-earth, self-possessed woman at the top of her field, your Steffi Graf’s, Sheryl Swoopes’s, but I will take a free breakfast buffet anytime, anyplace.", room_id: 7)
Message.create(user_id: 3, body: "https://gist.github.com/6903ebb9eab0583cd02d84171e2d638a", room_id: 7)
Message.create(user_id: 4, body: "There's been a mistake. You've accidentally given me the food that my food eats.", room_id: 7)
Message.create(user_id: 3, body: "Salad is traditionally the first course of a wedding.", room_id: 7)
Message.create(user_id: 4, body: "Is a gerbil marrying a rabbit?", room_id: 7)

Room.create(title: 'jerry', channel: true)
RoomUser.create(room_id: 8, user_id: 1)
RoomUser.create(room_id: 8, user_id: 3)
RoomUser.create(room_id: 8, user_id: 5)
RoomUser.create(room_id: 8, user_id: 7)
RoomUser.create(room_id: 8, user_id: 8)
Message.create(user_id: 8, body: "I really wish I could have your body.", room_id: 8)
Message.create(user_id: 7, body: "What?", room_id: 8)
Message.create(user_id: 5, body: "Eww, like tied up naked in your basement?", room_id: 8)
Message.create(user_id: 8, body: "No, no I mean you’re in good shape and you can eat whatever you want.", room_id: 8)
Message.create(user_id: 1, body: "That was weird, Jerry.", room_id: 8)
Message.create(user_id: 3, body: "https://gist.github.com/591954863bbd97e553dbfa0b8adacbd3", room_id: 8)
Message.create(user_id: 1, body: "So let’s talk sched, guys. Um, the kids are gonna come at 9AM on Saturday, and everyone’s gonna do Santa for two hours, so I would just advise everyone before you get into your costume to go to the bathroom so we can avoid what happened last year.", room_id: 8)
Message.create(user_id: 8, body: "It was just farts.", room_id: 8)

Room.create(title: "ron's_will", channel: true)
RoomUser.create(room_id: 9, user_id: 3)
RoomUser.create(room_id: 9, user_id: 4)
Message.create(user_id: 4, body: "That’s your will? You need that many pages to say 'Give my stuff to my wife'?", room_id: 9)
Message.create(user_id: 3, body: "It’s a complicated legal document.", room_id: 9)
Message.create(user_id: 4, body: "Doesn’t have to be. I’ve had the same will since I was 8 years old.", room_id: 9)
Message.create(user_id: 3, body: "(Reading Ron’s will) 'Upon my death all of my belongings shall transfer to the man or animal who has killed me.'", room_id: 9)
Message.create(user_id: 3, body: "What are these weird symbols?", room_id: 9)
Message.create(user_id: 4, body: "The man who kills me will know.", room_id: 9)

Room.create(title: 'tom_quotes', channel: true)
RoomUser.create(room_id: 10, user_id: 7)
Message.create(user_id: 7, body: "Yes, I’m married. But my wife understands that a good politician has to be appealing to the ladies. The fact that I haven’t even gotten close to cheating on her is a disappointment to both of us.", room_id: 10)
Message.create(user_id: 7, body: "How do you make any event classy on a budget? Red carpet. My entire apartment is red carpet. On top of that, leading into my bedroom, a second red carpet. Oh, what’s this in my shoe? Red carpet insole. Everywhere I go, I’m walking on red carpet.", room_id: 10)
Message.create(user_id: 7, body: "Sometimes you gotta work a little, so you can ball a lot.", room_id: 10)
Message.create(user_id: 7, body: "When I bet on horses, I never lose. Why? I bet on all the horses.", room_id: 10)
Message.create(user_id: 7, body: "I have never taken the high road. But I tell other people to ‘cause then there’s more room for me on the low road.", room_id: 10)

Room.create(title: 'andy_quotes', channel: true)
RoomUser.create(room_id: 11, user_id: 3)
RoomUser.create(room_id: 11, user_id: 6)
Message.create(user_id: 6, body: "From now on, we will be using code names. You can address me as Eagle 1. Ann, code name -- Been There, Done That. April is -- Currently Doing That. Donna is -- It Happened Once in a Dream. Chris, code name -- If I Had To Pick a Dude.", room_id: 11)
Message.create(user_id: 6, body: "Ben is -- Eagle Two.", room_id: 11)
Message.create(user_id: 3, body: "Oh, thank God.", room_id: 11)
Message.create(user_id: 6, body: "If you rearrange the letters of Peru, you get Europe.", room_id: 11)
Message.create(user_id: 6, body: "I’m not crying, okay? I’m just allergic to jerks!", room_id: 11)
Message.create(user_id: 6, body: "Just remember, every time you look up at the moon, I, too, will be looking at a moon. Not the same moon, obviously. That’s impossible.", room_id: 11)
Message.create(user_id: 3, body: "https://gist.github.com/6903ebb9eab0583cd02d84171e2d638a", room_id: 11)
Message.create(user_id: 6, body: "@swanson: Your secret is safe with me. And to even it out, I’m going to tell you all of my secrets.", room_id: 11)
Message.create(user_id: 6, body: "I once forgot to brush my teeth for five weeks.", room_id: 11)
Message.create(user_id: 6, body: "I didn’t actually sell my last car; I just forgot where I parked it.", room_id: 11)
Message.create(user_id: 6, body: "I don’t know who Al Gore is, and at this point I’m too afraid to ask.", room_id: 11)
Message.create(user_id: 6, body: "When they say 2% milk, I don’t know what the other 98% is.", room_id: 11)
Message.create(user_id: 6, body: "When I was a baby, my head was so big scientists did experiments on me.", room_id: 11)
Message.create(user_id: 6, body: "I once threw beer at a swan, and then it attacked my niece Rebecca.", room_id: 11)

Room.create(title: 'april_quotes', channel: true)
RoomUser.create(room_id: 12, user_id: 3)
RoomUser.create(room_id: 12, user_id: 5)
Message.create(user_id: 5, body: "We have a couple of house rules, though. You can’t use the front door; you have to climb in through the back window. No personal phone conversations. If you ever speak to me in Spanish, please use the formal “usted.” And no electricity after 6:00 PM. A couple more rules: if you ever watch a sad movie, you have to wear mascara so we can see whether or not you’ve been crying. There’s no noise allowed on Mondays. And no TV after breakfast.", room_id: 12)
Message.create(user_id: 3, body: "https://gist.github.com/6903ebb9eab0583cd02d84171e2d638a", room_id: 12)
Message.create(user_id: 5, body: "Hi, I’m April Ludgate. I’m 20 years old and I like people, places, and things.", room_id: 12)
Message.create(user_id: 5, body: "My mom's Puerto Rican. That's why I'm so lively and colorful.", room_id: 12)
Message.create(user_id: 5, body: "I wanted to make fun of stupid people while I get drunk. My two true passions.", room_id: 12)

Room.create(title:'knope,ann', channel: false)
Room.create(title:'april,knope', channel: false)
RoomUser.create(room_id: 13, user_id: 1)
RoomUser.create(room_id: 13, user_id: 2)
RoomUser.create(room_id: 14, user_id: 1)
RoomUser.create(room_id: 14, user_id: 5)
RoomUser.create(room_id: 14, user_id: 6)

Favorite.create(user_id: 1, fav_message_id: 52)
Favorite.create(user_id: 1, fav_message_id: 62)

Favorite.create(user_id: 2, fav_message_id: 10)
Favorite.create(user_id: 2, fav_message_id: 11)
Favorite.create(user_id: 2, fav_message_id: 12)
Favorite.create(user_id: 2, fav_message_id: 13)
Favorite.create(user_id: 2, fav_message_id: 14)
Favorite.create(user_id: 2, fav_message_id: 15)
Favorite.create(user_id: 2, fav_message_id: 16)
Favorite.create(user_id: 2, fav_message_id: 17)

Favorite.create(user_id: 3, fav_message_id: 10)

Favorite.create(user_id: 5, fav_message_id: 5)
Favorite.create(user_id: 5, fav_message_id: 46)
Favorite.create(user_id: 5, fav_message_id: 47)
Favorite.create(user_id: 5, fav_message_id: 49)
Favorite.create(user_id: 5, fav_message_id: 50)
Favorite.create(user_id: 5, fav_message_id: 51)
